CREATE DATABASE form_people_db;

use form_people_db;

CREATE TABLE PERSON(
    I_CODE INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    C_NAME VARCHAR(255) NOT NULL,
    C_EMAIL VARCHAR (255) NOT NULL,
    C_CITY VARCHAR(45) NOT NULL,
    C_COMPANY VARCHAR (255) NOT NULL,
    c_DESCRIPTION VARCHAR(300) NOT NULL,
    F_DATE_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

